# Generated by Django 5.1.1 on 2024-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=1, upload_to='News/'),
            preserve_default=False,
        ),
    ]
