# Generated by Django 5.1.1 on 2024-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_news_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sort_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
