# Generated by Django 5.1.1 on 2024-09-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_newslatter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='website',
            new_name='subject',
        ),
    ]
