# Generated by Django 5.1.1 on 2024-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_website_comment_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flickr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='flickr/')),
            ],
        ),
    ]
