# Generated by Django 5.1.1 on 2024-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_flickr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='emailComment',
        ),
    ]
